USE moviemania;


CREATE TABLE MOVIE (
 MOV_ID  Integer  NOT NULL,
 MOV_TITHLE VARCHAR(15)  NULL,
 MOV_YEAR Integer NOT NULL,
 MOV_TIME INTEGER NOT NULL,
 MOV_LANG VARCHAR(15) NULL,
 MOV_DT_REL Integer NOT NULL,
 MOVIE_REL_COUNTRY VARCHAR(15) NOT NULL,
 CONSTRAINT              MOVIE_PK       PRIMARY KEY(MOV_ID)
 );
 
 CREATE TABLE MOVIE_CAST (
   ACT_ID Integer NOT NULL,
   MOV_ID Integer NOT NULL,
   MOV_ROLE VARCHAR(30) NOT NULL,
   CONSTRAINT  MOVIE_CAST1_FK FOREIGN KEY(ACT_ID)
   REFERENCES ACTOR(Act_ID),
   CONSTRAINT  MOVIE_CAST2_FK FOREIGN KEY(MOV_ID)
   REFERENCES MOVIE(MOV_ID)
   );
   
   CREATE TABLE REVIEWER (
   REV_ID Integer NOT NULL,
   REV_NAME VARCHAR (30),
   CONSTRAINT REVIEWER_PK PRIMARY KEY(REV_ID)
);   

CREATE TABLE GENRES (
 GEN_ID Integer NOT NULL,
 GEN_TITHLE VARCHAR (20),
 CONSTRAINT  GENRES_PK  PRIMARY KEY(GEN_ID)
 );
   CREATE TABLE MOVIE_GENRES (
   MOV_ID Integer NOT NULL,
   GEN_ID Integer NOT NULL,
   CONSTRAINT  MOVIE_GENRES_FK  FOREIGN KEY(MOV_ID)
   REFERENCES MOVIE (MOV_ID),
   CONSTRAINT  MOVIE_GENRES2_FK  FOREIGN KEY(GEN_ID)
   REFERENCES GENRES (GEN_ID)
    );
    SELECT *
    FROM RATING;
	
   CREATE TABLE RATING (
   MOV_ID Integer NOT NULL,
   REV_ID Integer NOT NULL,
   REV_STARS Integer NOT NULL,
   NUM_O_RATINGS Integer NOT NULL,
   CONSTRAINT  RATING_FK  FOREIGN KEY(MOV_ID)
   REFERENCES MOVIE(MOV_ID),
   CONSTRAINT  RATING1_FK2  FOREIGN KEY(REV_ID)
   REFERENCES REVIEWER(REV_ID)
   );
 
 CREATE TABLE ACTOR (
 ACT_ID Integer NOT NULL,
 ACT_FNAME VARCHAR(20) NOT NULL,
 ACT_LNAME VARCHAR (20)NOT NULL,
 ACT_GENDER VARCHAR (1) NOT NULL,
 CONSTRAINT  ACTOR_GENRES_PK  primary KEY(ACT_ID)
 );
 
 CREATE TABLE DIRECTOR (
 DIR_ID Integer NOT NULL,
 DIR_FNAME VARCHAR(20) NOT NULL,
 DIR_LNAME VARCHAR(20) NOT NULL,
 CONSTRAINT DIRECTOR_PK PRIMARY KEY(DIR_ID)
 );
 
 CREATE TABLE MOVIE_DIRECTOR (
 DIR_ID Integer NOT NULL,
 MOV_ID Integer NOT NULL,
 CONSTRAINT MOVIE_DIRECTOR_FK FOREIGN KEY (DIR_ID)
 REFERENCES DIRECTOR(DIR_ID),
 CONSTRAINT MOVIE2_DIRECTOR2_FK FOREIGN KEY (MOV_ID)
 REFERENCES MOVIE(MOV_ID)
 );
 

