INSERT INTO MOVIE VALUES (
'1', 'Home Alone','1998','10','English',1998-10-10,'America');
INSERT INTO MOVIE VALUES (
'2', 'American Beauty','1999','3','English',1999-04-03,'America');
INSERT INTO MOVIE VALUES (
'3','Eyes Wide Open','1999','3','Africans',1998-01-01,'Banglore');
INSERT INTO MOVIE VALUES (
'4','GAME OF THRONES','2021','2','English',2008-04-03,'America');
INSERT INTO MOVIE VALUES (
'5','Scar Face','1997','2','Spanish',2006-04-05,'Mexico');


INSERT INTO MOVIE_CAST VALUES (
'001','1','ASSASIN');
INSERT INTO MOVIE_CAST VALUES (
'002','2','PRINCESS');
INSERT INTO MOVIE_CAST VALUES (
'003','3','LANISTER');
INSERT INTO MOVIE_CAST VALUES (
'004','4','White Walker');
INSERT INTO MOVIE_CAST VALUES (
'005','5','STARK');

INSERT INTO REVIEWER VALUES (
'100', 'OSCAR');
INSERT INTO REVIEWER VALUES (
'200', 'OLIVER');
INSERT INTO REVIEWER VALUES (
'300','ROLAND');
INSERT INTO REVIEWER VALUES (
'400','SPARROW');
INSERT INTO REVIEWER VALUES (
'500','SPIELBERG');

INSERT INTO GENRES VALUES (
'01','ACTION');
INSERT INTO GENRES VALUES (
'02','ROMANCE');
INSERT INTO GENRES VALUES (
'03','ACTION');
INSERT INTO GENRES VALUES (
'04','THRILLER');
INSERT INTO GENRES VALUES (
'05','FAIRYTALE');

INSERT INTO MOVIE_GENRES VALUES (
'1','01');
INSERT INTO MOVIE_GENRES VALUES (
'2','02');rating
INSERT INTO MOVIE_GENRES VALUES (
'3','03');
INSERT INTO MOVIE_GENRES VALUES (
'4','04');
INSERT INTO MOVIE_GENRES VALUES (
'5','05');



INSERT INTO RATING VALUES (
'1', '100','3.0','1000');
INSERT INTO RATING VALUES (
'2', '200','0.0','2000');
INSERT INTO RATING VALUES (
'3','300','5.0','3000');
INSERT INTO RATING VALUES (
'4','400','6.0','4000');
INSERT INTO RATING VALUES (
'5','500','7.0','5000');



INSERT INTO ACTOR VALUES (
'001','Jack','Baur','M');
INSERT INTO ACTOR VALUES (
'002','Eedris','Elber','M');
INSERT INTO ACTOR VALUES (
'003','Sharon','Stone','F');
INSERT INTO ACTOR VALUES (
'004','Regina','Askia','F');
INSERT INTO ACTOR VALUES (
'005','Shakh-Rukh','Khan','M');

INSERT INTO DIRECTOR VALUES (
'10.0','John','Smith');
INSERT INTO DIRECTOR VALUES (
'20.0','Peter','Parker');
INSERT INTO DIRECTOR VALUES (
'30.0','Lens','Armstrong');
INSERT INTO DIRECTOR VALUES (
'40.0','Niel','Flynn');
INSERT INTO DIRECTOR VALUES (
'50.0','Todd','Smith');

INSERT INTO MOVIE_DIRECTOR VALUES (
'10.0','1');
INSERT INTO MOVIE_DIRECTOR VALUES (
'20.0','2');
INSERT INTO MOVIE_DIRECTOR VALUES (
'30.0','3');
INSERT INTO MOVIE_DIRECTOR VALUES (
'40.0','4');
INSERT INTO MOVIE_DIRECTOR VALUES (
'50.0','5');



